services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nextjsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - custom-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  postgres_data:

networks:
  custom-network:
    driver: bridge
